### ISSUE TITLE
A issue with attributes

### ISSUE THREAD

**Issue by Karashok-Leo** [cleannrooster/extraspellattributes#7]
https://github.com/cleannrooster/extraspellattributes/blob/b41f41b61e791d62417e3b5688596a3365ea71cc/src/main/java/com/extraspellattributes/mixin/AttributeMixin.java#L105

generic_attack_damage may not exist

net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage
	at net.minecraft.class_5132.method_26865(class_5132.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_5132.method_26862(class_5132.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_5131.handler$chk000$extraspellattributes$getAttributeValueCONVERTFROM(class_5131.java:1105) ~[client-intermediary.jar:?]
	at net.minecraft.class_5131.method_26852(class_5131.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_26825(class_1309.java:1904) ~[client-intermediary.jar:?]
	at com.extraspellattributes.ReabsorptionInit.lambda$onInitialize$1(ReabsorptionInit.java:124) ~[extraspellattributes-1.2.16.jar:?]
	at net.spell_power.api.SpellSchool.getValue(SpellSchool.java:119) ~[spell_power-0.12.0+1.20.1.jar:?]
	at net.spell_power.api.SpellPower.getSpellPower(SpellPower.java:96) ~[spell_power-0.12.0+1.20.1.jar:?]
	at karashokleo.spell_dimension.util.DamageUtil.calculateDamage(DamageUtil.java:16) ~[spell_dimension-0.4.5.jar:?]
	at karashokleo.spell_dimension.content.effect.FrostedEffect.method_5572(FrostedEffect.java:27) ~[spell_dimension-0.4.5.jar:?]
	at net.minecraft.class_1293.method_5589(class_1293.java:209) ~[client-intermediary.jar:?]
	at net.minecraft.class_1293.method_5585(class_1293.java:182) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_6050(class_1309.java:814) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5670(class_1309.java:457) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5670(class_1308.java:284) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_5773(class_1297.java:474) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2380) ~[client-intermediary.jar:?]
	at net.minecraft.class_1308.method_5773(class_1308.java:351) ~[client-intermediary.jar:?]
	at net.minecraft.class_1593.method_5773(class_1593.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:480) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:385) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:353) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[client-intermediary.jar:?]
	... 5 more

**Comment by cleannrooster** [comment]
Hi, which version of Minecraft is this?

**Comment by Karashok-Leo** [comment]
1.20.1fabric

**Comment by cleannrooster** [comment]
I'm not sure what is causing this but I added a failsafe just in case
